### ISSUE TITLE
Update to `angular` package instead of `urigo:angular`

### ISSUE THREAD

**Issue by Urigo** [ParamountVentures/meteor-ionic-starter#1]
We now have the official `angular` package.
It's still the same thing but moving forward `angular` is the package to use

**Comment by stevenlivz** [comment]
Ok - thanks for the tip. That has now been updated in the comments and code https://github.com/ParamountVentures/meteor-ionic-starter/commit/dc44dba791df5f7d15dfdc66ee119520310bbe66
